# Generated by Django 5.2.8 on 2025-12-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('hall_ticket_number', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('EEE', 'EEE'), ('AIML', 'AIML'), ('AIDS', 'AIDS')], max_length=10)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
    ]
