# Generated by Django 5.2.8 on 2025-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_number', models.CharField(max_length=10)),
                ('m1', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Drawing', models.IntegerField()),
            ],
        ),
    ]
